### ISSUE TITLE
Morty behind Nginx Reverse Proxy won´t work

### ISSUE THREAD

**Issue by Happyfeet01** [asciimoo/morty#95]
Hello

i have setup Searx in an Docker-Container and it works. But when i try to access Morty with the URL https://suche.dasnetzundich.de/morty i get an 502 Error.
The Container is listen to 127.0.0.1:3000 also the Nginx Settings for Searx are correct. Can Anyone help me?

`[error] 29070#29070: *543 connect() failed (111: Connection refused) while connecting to upstream, client: 54.36.xxx.xx, server: suche.dasnetzundich.de, request: "GET /morty/?mortyurl=https%3A%2F%2Fwww.domain-tld%2Fstore%2Fpc%2Fviewcontent.asp%3Fidpage%3D5 HTTP/2.0", upstream: "http://10.10.10.5:80/morty/?mortyurl=https%3A%2F%2Fwww.domain.tld%2Fstore%2Fpc%2Fviewcontent.asp%3Fidpage%3D5", host: "suche.dasnetzundich.de"`

**Comment by maxweisspoker** [comment]
I ran into that exact same issue. It appears that the problem was created here:

[https://github.com/asciimoo/morty/commit/a549f668b4cf8cf79320e252cd05f6a0f02191b8#diff-ba7688b9e1bd5a1ac02d41cb4a46feffL989](https://github.com/asciimoo/morty/commit/a549f668b4cf8cf79320e252cd05f6a0f02191b8#diff-ba7688b9e1bd5a1ac02d41cb4a46feffL989)

and the "-listen" command line parameter is being ignored. I don't know enough to parse through how the config works in order to create a pull request, but that's almost certainly what's going on.  In the meantime, the fix that worked for me was setting the env var "MORTY_ADDRESS" to the listen address and port (e.g. "192.168.10.10:3000")

**Comment by Happyfeet01** [comment]
Yes that was the problem
